### ISSUE TITLE
I saw the api everywhere

### ISSUE THREAD

**Issue by kevin25** [CodeBradley/contact-form-7-rest-api#3]
Hello,

I saw the script like this /wp-json/contact-form-7/v1/contact-forms/11922/refill every page. I just want to disable it except for contact and subscription page. How can i do that? I'm using WooCommerce.

Thank

**Comment by CodeBradley** [comment]
I recommend looking at the official Contact Form 7 API. This project wasn't completed because they rolled out their own version.
