### ISSUE TITLE
Post always error "code": "rest_no_route" 

### ISSUE THREAD

**Issue by cahyofendhi** [CodeBradley/contact-form-7-rest-api#4]
i have website and mobile, 
i want to post same data from mobile using api, but when i try using postman always 

> {
    "code": "rest_no_route",
    "message": "Tidak ada rute yang sesuai dengan metode URL dan permintaan",
    "data": {
        "status": 404
    }
}
> 
this is my endpoint 

> http://dummy.com/wp-json/wpcf7/v1/forms 

(example)

can you help me, for this problem

**Comment by alejandro-moreno-mvd** [comment]
I've experimented this issue on the past and solved that with the permalink regeneration,
hope that helps
