### ISSUE TITLE
There is no Contact nav item and Redirect Settings

### ISSUE THREAD

**Issue by Barath-prakash** [CodeBradley/contact-form-7-rest-api#5]
In this plugin there is no contact nav link and no redirect settings. Give me some idea to get form and post data...

**Comment by CodeBradley** [comment]
This is an old project that is no longer maintained. CF7 has their own endpoints integrated within the plugin now; as the readme suggests. Use their code. If you're using an old version of CF7 then feel free to push any changes you make and I'll look over and approve them.
